name: CI
on: 
  workflow_dispatch:
    inputs:
      one:
        description: 'one'
        required: true
      two:
        description: 'two'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello, world!
